version: '3.5'
services:
  # MySQL servers
  mysql55:
    image: mysql:5.5
    expose:
      - 3306
    ports:
      - "$MYSQL55_PORT:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    volumes:
      - ./tests/db_fixtures/55-56:/docker-entrypoint-initdb.d
    command: --wait-timeout=2
    healthcheck:
      test: mysqladmin -h 127.0.0.1 ping
      interval: 10s
      timeout: 5m
      retries: 10
      start_period: 30s
    networks:
      - mitzasql-test-network
  mysql56:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "$MYSQL56_PORT:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    volumes:
      - ./tests/db_fixtures/55-56:/docker-entrypoint-initdb.d
    command: --wait-timeout=2
    healthcheck:
      test: mysqladmin -h 127.0.0.1 ping
      interval: 10s
      timeout: 5m
      retries: 10
      start_period: 30s
    networks:
      - mitzasql-test-network
  mysql57:
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - "$MYSQL57_PORT:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    volumes:
      - ./tests/db_fixtures/57-58:/docker-entrypoint-initdb.d
    command: --wait-timeout=2
    healthcheck:
      test: mysqladmin -h 127.0.0.1 ping
      interval: 10s
      timeout: 5m
      retries: 10
      start_period: 30s
    networks:
      - mitzasql-test-network
  mysql8:
    image: mysql:8
    expose:
      - 3306
    ports:
      - "$MYSQL8_PORT:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    volumes:
      - ./tests/db_fixtures/57-58:/docker-entrypoint-initdb.d
    command: --wait-timeout=2
    healthcheck:
      test: mysqladmin -h 127.0.0.1 ping
      interval: 10s
      timeout: 5m
      retries: 10
      start_period: 30s
    networks:
      - mitzasql-test-network
  # Python versions
  python35:
    build:
      context: .
      args:
        VERSION: 3.5
        TOXENV: py35
        USER_ID: $USER_ID
    environment:
      - "TOXENV=py35"
      - "USER_ID=$USER_ID"
    command: python --version
    depends_on:
      - mysql55
      - mysql56
      - mysql57
      - mysql8
    networks:
      - mitzasql-test-network
  python36:
    build:
      context: .
      args:
        VERSION: 3.6
        TOXENV: py36
        USER_ID: $USER_ID
    environment:
      - "TOXENV=py36"
      - "USER_ID=$USER_ID"
    command: python --version
    depends_on:
      - mysql55
      - mysql56
      - mysql57
      - mysql8
    networks:
      - mitzasql-test-network
  python37:
    build:
      context: .
      args:
        VERSION: 3.7
        TOXENV: py37
        USER_ID: $USER_ID
    environment:
      - "TOXENV=py37"
      - "USER_ID=$USER_ID"
    command: python --version
    depends_on:
      - mysql55
      - mysql56
      - mysql57
      - mysql8
    networks:
      - mitzasql-test-network
  python38:
    build:
      context: .
      args:
        VERSION: 3.8-rc
        TOXENV: py38
        USER_ID: $USER_ID
    environment:
      - "TOXENV=py38"
      - "USER_ID=$USER_ID"
    command: python --version
    depends_on:
      - mysql55
      - mysql56
      - mysql57
      - mysql8
    networks:
      - mitzasql-test-network

networks:
  mitzasql-test-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.5/24
